In [10]:
#Vectorization
import numpy as np
text1 = "How dare you! You can't do that!"
arr = np.array(text1.split(" "))
print(arr)
#lnth = np.vectorize(len)
#print(arr[lnth(arr)<4])
print(arr[(np.vectorize(len)) (arr) < 4])

['How' 'dare' 'you!' 'You' "can't" 'do' 'that!']
['How' 'You' 'do']


In [44]:
arr2 = np.zeros([5,4,3,2])
arr2[:,:,:1,:] = 5
print(arr2.shape)
print(arr2)

(5, 4, 3, 2)
[[[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]


 [[[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]

  [[5. 5.]
   [0. 0.]
   [0. 0.]]]]


In [51]:
#np.fabs? - Opens Documentation - float absolute
np.fabs?

In [55]:
np.abs([-1,1])

array([1, 1])

In [75]:
arr3 = np.arange(1,11)
#np.where?
np.where(arr3>5, arr3, arr3*10)

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10])

In [86]:
#arr.transpose - Inverse Dimensions(Columns = rows and vice versa)
#mean()
#cumsum()
#cumprod()
print(arr3.mean())
print(arr3.cumsum())
print(arr3.cumprod())
print(arr3.sum())
print(arr3.any())
print(arr3.all())

5.5
[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]
55
True
True


In [112]:
boolarr = [arr3 > 0]
any(arr3 < 11)
any?

In [113]:
all(arr3==99)
all?

In [114]:
np.sum(arr3)

55

In [117]:
arr4 = np.zeros(5)
np.unique(arr4) #Returns Unique and SORTED Value

array([0.])

In [118]:
np.save? #Data is saved and file is created.

In [124]:
np.save("abc", arr3)
arr3 = arr3*10
print(arr3)

[ 10  20  30  40  50  60  70  80  90 100]


In [125]:
np.load('abc.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [142]:
np.savez?
np.savez('savezfile', a = arr3, b = arr3+10, c = arr3*10)

In [148]:
dic = np.load('savezfile.npz')
print(dic['a'])
print(dic['b'])
print(dic['c'])

[ 10  20  30  40  50  60  70  80  90 100]
[ 20  30  40  50  60  70  80  90 100 110]
[ 100  200  300  400  500  600  700  800  900 1000]


In [165]:
arr4 = np.arange(1,5)
np.random.seed(7) #Saves Random number in seed 7
perm = np.random.rand(3)
print(perm)

[0.07630829 0.77991879 0.43840923]


In [166]:
#np.random.seed(7)
perm = np.random.rand(3) #Called without seed.
print(perm)
np.random.seed(7) #Called with seed
perm = np.random.rand(3)
print(perm)

[0.72346518 0.97798951 0.53849587]
[0.07630829 0.77991879 0.43840923]


In [167]:
print(arr4)
print(arr4.reshape((2,2),order = "F")) #Fortans order

[1 2 3 4]
[[1 3]
 [2 4]]


In [176]:
#np.concatenate(arr4, axis = 0)
#np.vstack?
#np.hstack?

In [191]:
arr5 = np.arange(10,200,10)
print(np.split(arr5, [2,7]))

[array([10, 20]), array([30, 40, 50, 60, 70]), array([ 80,  90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190])]


In [196]:
arr6 = np.split(arr5,[2,4,6,8])
print(arr6)
a,b,c,d,e = arr6
print("\n")

print(a) #print(arr6[0])
print(b)
print(c)
print(d)
print(e)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([ 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190])]


[10 20]
[30 40]
[50 60]
[70 80]
[ 90 100 110 120 130 140 150 160 170 180 190]


In [220]:
import matplotlib.pylab as plt
im = plt.imread("names.PNG")
print(type(im))
print(im.shape)
#print(im[:,:,:])
photos = np.zeros([20,371,1273,4])
photos[0] = im
print(photos[0][:3,:5,:4]) #Storing Photo in Array
#Library PIL and os (Download 20 pics and resize to 512,512,3) (Use Files Names as Array or some kahani)

<class 'numpy.ndarray'>
(371, 1273, 4)
[[[1.         1.         1.         0.87058824]
  [1.         1.         1.         0.87058824]
  [1.         1.         1.         0.98823529]
  [1.         1.         1.         1.        ]
  [0.99607843 0.99607843 0.99607843 0.96078432]]

 [[1.         1.         1.         0.87058824]
  [1.         1.         1.         0.87058824]
  [1.         1.         1.         0.98823529]
  [1.         1.         1.         1.        ]
  [0.99607843 0.99607843 0.99607843 0.96078432]]

 [[1.         1.         1.         0.93333334]
  [1.         1.         1.         0.93333334]
  [1.         1.         1.         1.        ]
  [1.         1.         1.         1.        ]
  [0.98039216 0.98039216 0.98039216 1.        ]]]
