# Review Test Analysis

In [2]:
# -Using Reviews
#   -Gather Data and Save in a file(JSON).
#   -Label the Data
#   -Load Data in memory in a list(s)
#   -Make a word list for positive and negative.
#   -give input and get output
#   -test output with original data
#   -Calulate Accuracy.
#   -Feed more reviews to increase accuracy using prediction
#   -Try at HOME using split.
# Ai_Anees_Ahmed - slack
# AI AneedAhmed - FB
# Beautiful Soup Data Scrapping.
# Saylani@729


# NumPy

In [3]:
#Uses Arrays for direct access.
#Linked Lists do not offer direct access
#Arrays can be multiplied together using a * b where a and b are arrays.
#nd-array: Data of same type, large datasets.
#%time used for getting time of line execution/process.

In [4]:
import numpy as np
a = np.arange(1000000)
Mylist = list(range(1000000))

In [5]:
%time for _ in range(10): a2 = a * 2 # CPU times: user 20 ms, sys: 50 ms, total: 70 ms Wall time: 72.4 ms

Wall time: 110 ms


In [6]:
%time for _ in range(10): Mylist2 = [x * 2 for x in Mylist]# CPU time: user 760 ms, sys: 290ms, total: 1.05 s, Wall time: 1.05 s

Wall time: 5.1 s


In [7]:
#Creating nd-array
#---slide...
nd_array= np.array([1,2,3,4])
print(nd_array)
print(type(nd_array))

list1 = [2,3,4,5,6]
nd_arra = np.array(list1)
print(nd_arra)
print(type(list1))

[1 2 3 4]
<class 'numpy.ndarray'>
[2 3 4 5 6]
<class 'list'>


In [8]:

n_a = np.zeros([5,3])
print(n_a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
n_b = np.ones([1,2])
print(n_b)

[[1. 1.]]


In [10]:
n_c = np.empty([2,2]) #Used to save time.
print(n_c)

[[1.37961981e-306 1.11258446e-306]
 [6.23059726e-307 9.34609790e-307]]


In [11]:
n_d = np.arange(10)
print(n_d)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
n_e = np.zeros([1,2,3,4]) #4-dimentional array
print(n_e)

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [13]:
#irus (phool) data
#Data Scrapping
#Git Video's and quiz. Will not be discussed in class.

# Attributes of Numpy

In [14]:
#shape is a attribute so no bracket.
na = np.zeros([3,2,4])
print(na.shape)
#dtype: NumPy Data Types
print(na.dtype)
#ndim: no. of dimensions
print(na.ndim)

#Always used along with object. No Parenthesis. 

(3, 2, 4)
float64
3
